version: '3'
services:
  backend:
    build:
      context: ./backend/
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - backend/.env

  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:8081"
    env_file:
      - frontend/.env
    depends_on:
      - backend
  
  db:
    image: postgres:14.6-alpine
    environment:
      POSTGRES_PASSWORD: people
      POSTGRES_USER: people
      POSTGRES_DB: people
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./database/crud_db.sql:/docker-entrypoint-initdb.d/crud_db.sql